---
output: html_document
runtime: shiny
---

## Welcome!

Thank you for your interest in using the *E.coli* data visualization tool. Deployed as a Shiny application, this tool is intended to assist Environmental Coordinators and Managers with total maximum daily load (TMDL) development under the [EPA's Clean Water Act](https://www.epa.gov/laws-regulations/summary-clean-water-act). Users may study time series plots, compare between sites, and ascertain which sites exceed water quality standards at what time(s) of year. Peruse this guide for more information on the plots displayed and their functionality within the app. Originally produced for the Utah Department of Environmental Quality's [Division of Water Quality](https://deq.utah.gov/division-water-quality).

### General Tips

**Navigation**
Use the tabs along the top of the page to navigate between plotting tools. Note that each page is independent from the others. Toggling between sites on one page does not affect the visualizations available on other tabs.

**Saving Plots**
To download a plot for later use, right click the plot and click "Save Image". Navigate to the appropriate folder, and provide an applicable name followed by the file extension (".jpg" or ".pdf").

**View Medians and Quartiles** 
On the Monthy, Rec/Non-Rec Season, and Irrigation/Non-Irrigation Season tabs, pages contain a checkbox labeled "View Medians and Quartiles". When checked, the plot will include a boxplot overlay on top of the barplots. The boxplots are an indicator of the spread of the data, and allow the user to see outliers and the range of the data. If the range of the data extend beyond the barplot extremes (as is often the case), the plot axes will change in scale. The lower whisker of each boxplot represents the lowest value, excluding outliers, while the upper whisker represents the highest value, excluding outliers. The top and bottom edges of each box indicate the 75th and 25th percentiles, respectively. Boxes without whiskers indicate only 2 data points exist, and median lines without a box indicate only 1 data point exists.

**Select Measurement Type**
On tabs displaying bar plots, the user may select whether they would like the plots to show concentration or loading data. Sites lacking flow (and thus loading) data will not have this functionality, and "Loading" will not be listed as an option in the drop down menu.
 

### Time Series

Within the time series plot, users can compare E.coli concentrations at different sites through time. Toggling from a "Point" plot type to a "Line" plot type connects the individual measurements for each site to provide a more cohesive picture of concentration changes over time. However, line plots can become busy if many sites are included on the graph.

Use the date range widget to focus on particular years or seasons. Clicking on the start or end date will bring up a calendar, including arrows to navigate forward and backward in time. Repeatedly clicking the title at the top of the date range menu will push out to months, years, decades, and so on. Click "Reset Date Range" to plot the sites against the maximum and minimum dates for which data are available in the dataset. Changing the date range also changes the number of points exceeding the maximum criterion, which is reflected in the plot legend.

Editing the Max and Geomean criteria moves the red and orange horizontal lines on the plot. Edits to the max criterion change the calculations for the percentage of datapoints exceeding the maximum criterion.

Note that the colors are not specific to each site, but rather reflect the order in which the checked sites appear in the checkbox menu. Clicking sites on and off will change the colors of the points visible on the plot. The legend reflects these changes.

### Monthly

Monthly barplots display the geometric mean *E.coli* concentrations/loadings calculated using all available data across all years. The colors of the bars are a gradient added for contrast and are not specific to each month. Note that the horizontal line plotted in all graphs is the geometric mean standard, and the percentage reported above certain bars represents the percent reduction needed to meet the geometric mean standard. Also be aware that quartiles may reveal points that fall above the geomean standard but are not consistent enough to push the geometric mean of the data above the standard. 

### Rec/Non-Rec Season

Barplots on this tab compare annual rec/non-rec season geomeans to one another across years. While selecting the concentration input yields only one graph, the loading input will produce two graphs, which separate recreation and non-recreation season data. This makes it easier to compare observed loading data to loading capacity. However, y-axis limits are identical in both plots to allow for easy comparison between recreation and non-recreation seasons. Similar to the Monthly tab, the percentage reported above certain bars represents the percent reduction needed to meet the loading capacity with a margin of safety.

### Irrigation/Non-Irrigation Seasons

Barplots in this tab compare annual irrigation/non-irrigation season geomeans to one another across years, and function exactly as in the rec/non-rec season tab.

### Load Duration Curves

This tab only appears when the dataset contains loading data and constructs a load duration curve plot. The plot overlays *E.coli* loadings on loading capacities, ordered based on flow percentile. Observed loading points populating the left side of the graph occur at high flows, while loadings populating the right side of the graph occur at low flows. Observed loadings are categorized as "exceeding" when they are located above the loading capacity + margin of safety (MOS) line. This is always the lower of the two lines, as it reflects the conservative approach commonly taken in [TMDL development] (https://www.epa.gov/sites/production/files/2015-07/documents/2007_08_23_tmdl_duration_curve_guide_aug2007.pdf).

Use the "Data Category" drop down menu to specify whether the loading points are categorized by calendar seasons, rec/non-rec seasons, and irrigation/non-irrigation seasons. Changing the drop-down selection will change the color of the points (but not their positions!) and provides insights toward the times of year in which exceedances are observed.

## Questions?

Contact Elise Hinman in the Division of Water Quality, Utah Department of Environmental Quality, at ehinman@utah.gov.

## Acknowledgments

Huge thank you to Jake Vander Laan within the Division of Water Quality for programming tips and patience discussing all things Shiny and R. Additional gratitude goes out to Jodi Gardberg, Amy Dickey, Sandy Wingert, and Lucy Parham for feedback on the application and its usefulness in drafting TMDLs. Finally, can't miss the giant community of amateur and professional programmers on Stack Overflow and GitHub, RStudio.com and its many help forums, DataCamp, and Data Science YouTube channels.
